### ISSUE TITLE
tcplPlotPlate doesn't work for single conc data

### ISSUE THREAD

**Issue by ericwatt** [daynefiler/tcpl#13]
```
dnames <- names(dat)
if ("m1id" %in% dnames) {lvl <- 1L; idnm <- "acid"; vlnm <- "rval"}
if ("m2id" %in% dnames) {lvl <- 2L; idnm <- "acid"; vlnm <- "cval"}
if ("m3id" %in% dnames) {lvl <- 3L; idnm <- "aeid"; vlnm <- "resp"}
if (is.null(lvl)) stop("Invalid dat input.")
```

Can rows for `s1id`, `s2id`, etc in `dnames` be added so that single conc data can be plotted as well?

**Comment by ericwatt** [comment]
FYI, CONTRIBUTING.md says "Label your issue accordingly" but I don't have permissions to label issues here. I would assume this is an enhancement.

**Comment by daynefiler** [comment]
Thanks, Eric. I realized the labeling was not open to everyone after writing that I will fix it.
