### ISSUE TITLE
spaces doesn't work with NA

### ISSUE THREAD

**Issue by ldecicco-USGS** [daynefiler/tcpl#19]
https://github.com/daynefiler/tcpl/blob/master/R/plotFit.R#L257

There's still interesting information in the text though.

**Comment by daynefiler** [comment]
@ldecicco-USGS I assume you are not using the development version hosted on this site? The bug arose from an R update, and has been fixed in issues #2 #9 and #15. Please update to the development version.

**Comment by ldecicco-USGS** [comment]
Cool, was just about to submit a PR, but that's even easier
