### ISSUE TITLE
plotFit error due to NA values in pars

### ISSUE THREAD

**Issue by martino165** [daynefiler/tcpl#9]
`.plotFit` error due to `NA` values in pars causing all aeid concentration response plotting routines to error out if newer versions of R are being used. Most likely interpretation of `nchar(NA)` needs to be converted to `nchar("NA")`

**Comment by daynefiler** [comment]
This is definitely related to #2. Other instances of `NA` need to be escaped in quotes.

**Comment by daynefiler** [comment]
Closed by #10
